# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arrai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arrai.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61rrai.proto\x12\x05proto\"6\n\tUpdateReq\x12\x0c\n\x04\x65xpr\x18\x01 \x01(\t\x12\x1b\n\x05param\x18\x02 \x01(\x0b\x32\x0c.proto.Value\"\x0b\n\tUpdateAck\"7\n\nObserveReq\x12\x0c\n\x04\x65xpr\x18\x01 \x01(\t\x12\x1b\n\x05param\x18\x02 \x01(\x0b\x32\x0c.proto.Value\"*\n\x0bObserveResp\x12\x1b\n\x05value\x18\x03 \x01(\x0b\x32\x0c.proto.Value\"|\n\x05Value\x12\x1f\n\x06number\x18\x01 \x01(\x0b\x32\r.proto.NumberH\x00\x12\x1d\n\x05tuple\x18\x02 \x01(\x0b\x32\x0c.proto.TupleH\x00\x12\x19\n\x03set\x18\x03 \x01(\x0b\x32\n.proto.SetH\x00\x12\x0e\n\x04json\x18\x04 \x01(\tH\x00\x42\x08\n\x06\x63hoice\"\x1d\n\x06Number\x12\x0b\n\x01n\x18\x01 \x01(\x01H\x00\x42\x06\n\x04repr\"k\n\x05Tuple\x12&\n\x05\x61ttrs\x18\x01 \x03(\x0b\x32\x17.proto.Tuple.AttrsEntry\x1a:\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.proto.Value:\x02\x38\x01\"\x9f\x01\n\x03Set\x12#\n\x06values\x18\x01 \x01(\x0b\x32\x11.proto.Set.ValuesH\x00\x12\x0e\n\x04\x62ool\x18\x02 \x01(\x08H\x00\x12\"\n\x05\x61rray\x18\x03 \x01(\x0b\x32\x11.proto.Set.ValuesH\x00\x12\x10\n\x06string\x18\x04 \x01(\tH\x00\x1a%\n\x06Values\x12\x1b\n\x05value\x18\x01 \x03(\x0b\x32\x0c.proto.ValueB\x06\n\x04repr2q\n\x05\x41rrai\x12\x32\n\x06Update\x12\x10.proto.UpdateReq\x1a\x10.proto.UpdateAck\"\x00(\x01\x30\x01\x12\x34\n\x07Observe\x12\x11.proto.ObserveReq\x1a\x12.proto.ObserveResp\"\x00\x30\x01\x62\x06proto3')
)




_UPDATEREQ = _descriptor.Descriptor(
  name='UpdateReq',
  full_name='proto.UpdateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expr', full_name='proto.UpdateReq.expr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='proto.UpdateReq.param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=76,
)


_UPDATEACK = _descriptor.Descriptor(
  name='UpdateAck',
  full_name='proto.UpdateAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=89,
)


_OBSERVEREQ = _descriptor.Descriptor(
  name='ObserveReq',
  full_name='proto.ObserveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expr', full_name='proto.ObserveReq.expr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='proto.ObserveReq.param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=146,
)


_OBSERVERESP = _descriptor.Descriptor(
  name='ObserveResp',
  full_name='proto.ObserveResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.ObserveResp.value', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=190,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='proto.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='proto.Value.number', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tuple', full_name='proto.Value.tuple', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set', full_name='proto.Value.set', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='json', full_name='proto.Value.json', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='choice', full_name='proto.Value.choice',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=192,
  serialized_end=316,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='proto.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='proto.Number.n', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='repr', full_name='proto.Number.repr',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=318,
  serialized_end=347,
)


_TUPLE_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='proto.Tuple.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Tuple.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Tuple.AttrsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=456,
)

_TUPLE = _descriptor.Descriptor(
  name='Tuple',
  full_name='proto.Tuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attrs', full_name='proto.Tuple.attrs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TUPLE_ATTRSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=456,
)


_SET_VALUES = _descriptor.Descriptor(
  name='Values',
  full_name='proto.Set.Values',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Set.Values.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=610,
)

_SET = _descriptor.Descriptor(
  name='Set',
  full_name='proto.Set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='proto.Set.values', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool', full_name='proto.Set.bool', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='array', full_name='proto.Set.array', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string', full_name='proto.Set.string', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SET_VALUES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='repr', full_name='proto.Set.repr',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=459,
  serialized_end=618,
)

_UPDATEREQ.fields_by_name['param'].message_type = _VALUE
_OBSERVEREQ.fields_by_name['param'].message_type = _VALUE
_OBSERVERESP.fields_by_name['value'].message_type = _VALUE
_VALUE.fields_by_name['number'].message_type = _NUMBER
_VALUE.fields_by_name['tuple'].message_type = _TUPLE
_VALUE.fields_by_name['set'].message_type = _SET
_VALUE.oneofs_by_name['choice'].fields.append(
  _VALUE.fields_by_name['number'])
_VALUE.fields_by_name['number'].containing_oneof = _VALUE.oneofs_by_name['choice']
_VALUE.oneofs_by_name['choice'].fields.append(
  _VALUE.fields_by_name['tuple'])
_VALUE.fields_by_name['tuple'].containing_oneof = _VALUE.oneofs_by_name['choice']
_VALUE.oneofs_by_name['choice'].fields.append(
  _VALUE.fields_by_name['set'])
_VALUE.fields_by_name['set'].containing_oneof = _VALUE.oneofs_by_name['choice']
_VALUE.oneofs_by_name['choice'].fields.append(
  _VALUE.fields_by_name['json'])
_VALUE.fields_by_name['json'].containing_oneof = _VALUE.oneofs_by_name['choice']
_NUMBER.oneofs_by_name['repr'].fields.append(
  _NUMBER.fields_by_name['n'])
_NUMBER.fields_by_name['n'].containing_oneof = _NUMBER.oneofs_by_name['repr']
_TUPLE_ATTRSENTRY.fields_by_name['value'].message_type = _VALUE
_TUPLE_ATTRSENTRY.containing_type = _TUPLE
_TUPLE.fields_by_name['attrs'].message_type = _TUPLE_ATTRSENTRY
_SET_VALUES.fields_by_name['value'].message_type = _VALUE
_SET_VALUES.containing_type = _SET
_SET.fields_by_name['values'].message_type = _SET_VALUES
_SET.fields_by_name['array'].message_type = _SET_VALUES
_SET.oneofs_by_name['repr'].fields.append(
  _SET.fields_by_name['values'])
_SET.fields_by_name['values'].containing_oneof = _SET.oneofs_by_name['repr']
_SET.oneofs_by_name['repr'].fields.append(
  _SET.fields_by_name['bool'])
_SET.fields_by_name['bool'].containing_oneof = _SET.oneofs_by_name['repr']
_SET.oneofs_by_name['repr'].fields.append(
  _SET.fields_by_name['array'])
_SET.fields_by_name['array'].containing_oneof = _SET.oneofs_by_name['repr']
_SET.oneofs_by_name['repr'].fields.append(
  _SET.fields_by_name['string'])
_SET.fields_by_name['string'].containing_oneof = _SET.oneofs_by_name['repr']
DESCRIPTOR.message_types_by_name['UpdateReq'] = _UPDATEREQ
DESCRIPTOR.message_types_by_name['UpdateAck'] = _UPDATEACK
DESCRIPTOR.message_types_by_name['ObserveReq'] = _OBSERVEREQ
DESCRIPTOR.message_types_by_name['ObserveResp'] = _OBSERVERESP
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Tuple'] = _TUPLE
DESCRIPTOR.message_types_by_name['Set'] = _SET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateReq = _reflection.GeneratedProtocolMessageType('UpdateReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREQ,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.UpdateReq)
  ))
_sym_db.RegisterMessage(UpdateReq)

UpdateAck = _reflection.GeneratedProtocolMessageType('UpdateAck', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEACK,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.UpdateAck)
  ))
_sym_db.RegisterMessage(UpdateAck)

ObserveReq = _reflection.GeneratedProtocolMessageType('ObserveReq', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVEREQ,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.ObserveReq)
  ))
_sym_db.RegisterMessage(ObserveReq)

ObserveResp = _reflection.GeneratedProtocolMessageType('ObserveResp', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVERESP,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.ObserveResp)
  ))
_sym_db.RegisterMessage(ObserveResp)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.Value)
  ))
_sym_db.RegisterMessage(Value)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.Number)
  ))
_sym_db.RegisterMessage(Number)

Tuple = _reflection.GeneratedProtocolMessageType('Tuple', (_message.Message,), dict(

  AttrsEntry = _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), dict(
    DESCRIPTOR = _TUPLE_ATTRSENTRY,
    __module__ = 'arrai_pb2'
    # @@protoc_insertion_point(class_scope:proto.Tuple.AttrsEntry)
    ))
  ,
  DESCRIPTOR = _TUPLE,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.Tuple)
  ))
_sym_db.RegisterMessage(Tuple)
_sym_db.RegisterMessage(Tuple.AttrsEntry)

Set = _reflection.GeneratedProtocolMessageType('Set', (_message.Message,), dict(

  Values = _reflection.GeneratedProtocolMessageType('Values', (_message.Message,), dict(
    DESCRIPTOR = _SET_VALUES,
    __module__ = 'arrai_pb2'
    # @@protoc_insertion_point(class_scope:proto.Set.Values)
    ))
  ,
  DESCRIPTOR = _SET,
  __module__ = 'arrai_pb2'
  # @@protoc_insertion_point(class_scope:proto.Set)
  ))
_sym_db.RegisterMessage(Set)
_sym_db.RegisterMessage(Set.Values)


_TUPLE_ATTRSENTRY.has_options = True
_TUPLE_ATTRSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_ARRAI = _descriptor.ServiceDescriptor(
  name='Arrai',
  full_name='proto.Arrai',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=620,
  serialized_end=733,
  methods=[
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='proto.Arrai.Update',
    index=0,
    containing_service=None,
    input_type=_UPDATEREQ,
    output_type=_UPDATEACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Observe',
    full_name='proto.Arrai.Observe',
    index=1,
    containing_service=None,
    input_type=_OBSERVEREQ,
    output_type=_OBSERVERESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARRAI)

DESCRIPTOR.services_by_name['Arrai'] = _ARRAI

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ArraiStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Update = channel.stream_stream(
          '/proto.Arrai/Update',
          request_serializer=UpdateReq.SerializeToString,
          response_deserializer=UpdateAck.FromString,
          )
      self.Observe = channel.unary_stream(
          '/proto.Arrai/Observe',
          request_serializer=ObserveReq.SerializeToString,
          response_deserializer=ObserveResp.FromString,
          )


  class ArraiServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Update(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ArraiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Update': grpc.stream_stream_rpc_method_handler(
            servicer.Update,
            request_deserializer=UpdateReq.FromString,
            response_serializer=UpdateAck.SerializeToString,
        ),
        'Observe': grpc.unary_stream_rpc_method_handler(
            servicer.Observe,
            request_deserializer=ObserveReq.FromString,
            response_serializer=ObserveResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proto.Arrai', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaArraiServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Update(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Observe(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaArraiStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Update(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    def Observe(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_Arrai_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('proto.Arrai', 'Observe'): ObserveReq.FromString,
      ('proto.Arrai', 'Update'): UpdateReq.FromString,
    }
    response_serializers = {
      ('proto.Arrai', 'Observe'): ObserveResp.SerializeToString,
      ('proto.Arrai', 'Update'): UpdateAck.SerializeToString,
    }
    method_implementations = {
      ('proto.Arrai', 'Observe'): face_utilities.unary_stream_inline(servicer.Observe),
      ('proto.Arrai', 'Update'): face_utilities.stream_stream_inline(servicer.Update),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Arrai_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('proto.Arrai', 'Observe'): ObserveReq.SerializeToString,
      ('proto.Arrai', 'Update'): UpdateReq.SerializeToString,
    }
    response_deserializers = {
      ('proto.Arrai', 'Observe'): ObserveResp.FromString,
      ('proto.Arrai', 'Update'): UpdateAck.FromString,
    }
    cardinalities = {
      'Observe': cardinality.Cardinality.UNARY_STREAM,
      'Update': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'proto.Arrai', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
